name: deploy-book

on:
  push:
    branches:
      - main

# ロボットに書き込み権限を明示的に与える
permissions:
  contents: write

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -U jupyter-book

    - name: Build the book
      run: |
        # コマンドが見つからないエラーを回避するため python -m で実行
        python -m jupyter_book build .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Jupyter Bookが生成したHTMLがある場所を指定
        publish_dir: ./_build/html
        # Jekyllを無効化するファイルを自動生成
        nojekyll: true 
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
